import markdownIt from "markdown-it";
import mathjax3 from "markdown-it-mathjax3";
import * as prettier from "prettier";
import { readFileSync } from "fs";
import { resolve } from "path";
import { defaultRenderers } from "./section-renderers/index.js";
import { buildCemContext } from "./section-renderers/build-cem-context.js";

/**
 * Reads the @docSections tag from a CEM declaration and returns
 * an array of section keys, or null if not present.
 */
function parseDocSections(decl) {
  const tag = decl.docSections;
  if (!tag) return null;
  const raw = [tag.name, tag.description].filter(Boolean).join(" ");
  if (!raw.trim()) return null;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * WTFM Eleventy plugin — registers shortcodes, filters, and
 * configuration for generating documentation from a Custom
 * Elements Manifest.
 *
 * ## Registered shortcodes
 *
 * - **`renderDocs(className)`** — renders the full documentation page
 *   for a web component by looking up its CEM declaration and running
 *   all configured section renderers.
 * - **`inlineSvg(fileName)`** — reads an SVG file from `assetsDir`
 *   and returns its content inline (with the XML declaration stripped).
 *
 * ## Registered filters
 *
 * - **`asset(name)`** — maps a logical asset name (e.g. `"docs.js"`)
 *   to its hashed filename via the asset manifest.
 *
 * ## Global data
 *
 * - **`customElements`** — the parsed Custom Elements Manifest object.
 *
 * @param {object} eleventyConfig - The Eleventy configuration object
 *   provided by Eleventy's plugin system.
 *
 * @param {object} options - Plugin options.
 *
 * @param {string} options.cemPath - Absolute or project-relative path
 *   to the `custom-elements.json` file generated by
 *   `@custom-elements-manifest/analyzer`. This is the only required
 *   option.
 *
 * @param {string[]} [options.excludeAttributes=[]] - Attribute names
 *   to hide from the generated documentation. Useful for excluding
 *   internal or inherited attributes that consumers don't need to see.
 *   For example, passing `["variant", "scheme"]` would suppress those
 *   attributes from every component's docs.
 *
 * @param {Object<string, string[]>} [options.attributeExceptions={}] -
 *   Overrides for `excludeAttributes` on a per-tag basis. Keys are
 *   attribute names (must also appear in `excludeAttributes`), values
 *   are arrays of tag names where that attribute should still be shown.
 *
 *   Example: to exclude `"scheme"` globally but still show it on
 *   `<my-root>`:
 *   ```js
 *   {
 *     excludeAttributes: ["scheme"],
 *     attributeExceptions: { "scheme": ["my-root"] },
 *   }
 *   ```
 *
 * @param {string} [options.assetsDir="assets"] - Directory used to
 *   resolve filenames passed to the `inlineSvg` shortcode.
 *
 * @param {function} [options.githubLinkTemplate] - Optional function
 *   that receives a GitHub URL string and returns an HTML string for
 *   the source-code link shown in each component's doc header.
 *   When omitted, a simple `<a href="..." target="_blank">GitHub</a>`
 *   link is generated.
 *
 *   Signature: `(url: string) => string`
 *
 * @param {(string|{key: string})[]} [options.sections] - Array of
 *   section keys (or objects with a `key` property) defining the
 *   default rendering order.  When omitted, the built-in order is
 *   used: `slots`, `attributes`, `methods`, `events`, `css-parts`,
 *   `css-properties`.
 *
 *   Individual components can override this order via the
 *   `@docSections` JSDoc tag in their source:
 *   - `@docSections all, -methods` — render all defaults except methods
 *   - `@docSections slots, attributes` — render only those two sections
 *
 * @param {object[]} [options.customRenderers] - Array of custom section
 *   renderer objects to register alongside the built-in renderers.
 *   Each renderer must conform to the `SectionRenderer` interface:
 *
 *   ```js
 *   {
 *     key: "my-section",         // unique section identifier
 *     async render(decl, options) {
 *       // decl  — CEM declaration for the component
 *       // options — resolved plugin options
 *       return "## My Section\n\nContent here.\n";
 *     }
 *   }
 *   ```
 *
 *   Custom renderers with a `key` matching a built-in renderer will
 *   replace that built-in. To include custom sections in the output,
 *   add their keys to the `sections` option or use `@docSections` in
 *   the component source.
 */
export default function wtfmPlugin(eleventyConfig, options = {}) {
  const {
    cemPath,
    excludeAttributes = [],
    attributeExceptions = {},
    assetsDir = "assets",
    githubLinkTemplate,
    sections,
    customRenderers,
  } = options;

  // ── Resolved options (passed to every renderer) ───────────────
  const resolvedOptions = {
    ...options,
    excludeAttributes,
    attributeExceptions,
    assetsDir,
    githubLinkTemplate,
  };

  // ── Build the renderer registry ───────────────────────────────
  const rendererMap = new Map();
  for (const r of defaultRenderers) {
    rendererMap.set(r.key, r);
  }
  if (customRenderers) {
    for (const r of customRenderers) {
      rendererMap.set(r.key, r);
    }
  }

  // Resolve the default section order
  const defaultSectionOrder = sections
    ? sections.map((s) => (typeof s === "string" ? s : s.key))
    : defaultRenderers.map((r) => r.key);

  // ── Load the Custom Elements Manifest ────────────────────────
  let customElements;
  try {
    customElements = JSON.parse(readFileSync(cemPath, "utf-8"));
  } catch (e) {
    console.warn("wtfm: Could not read custom-elements.json at", cemPath);
    customElements = { modules: [] };
  }

  // ── Markdown-it with mathjax3 ────────────────────────────────
  const mdOptions = {
    html: true,
    breaks: false,
    linkify: true,
  };
  const markdownLib = markdownIt(mdOptions).use(mathjax3);
  eleventyConfig.setLibrary("md", markdownLib);

  // ── Asset filter ─────────────────────────────────────────────
  eleventyConfig.addFilter("asset", function (value) {
    const manifest = this.data.manifest;
    if (manifest && manifest[value]) {
      return `${manifest[value]}`;
    }

    console.warn("Asset not found in manifest: " + value);
  });

  // ── Inline SVG shortcode ─────────────────────────────────────
  eleventyConfig.addShortcode("inlineSvg", function (fileName) {
    const svgPath = resolve(assetsDir, fileName);
    try {
      return readFileSync(svgPath, "utf-8").replace(/<\?xml[^?]*\?>\s*/, "");
    } catch (e) {
      console.warn("SVG not found: " + svgPath);
      return "";
    }
  });

  // ── renderDocs shortcode ─────────────────────────────────────
  eleventyConfig.addShortcode("renderDocs", async function (elementName) {
    const elemDocs = customElements.modules.find(
      (m) => m.declarations[0]?.name === elementName,
    )?.declarations[0];

    if (!elemDocs) {
      console.warn("wtfm: No CEM entry found for", elementName);
      return "";
    }

    // Header with tag name and optional GitHub link
    const githubUrl = elemDocs.github?.name;
    let githubLink = "";
    if (githubUrl) {
      if (githubLinkTemplate) {
        githubLink = githubLinkTemplate(githubUrl);
      } else {
        githubLink = `<a href="${githubUrl}" target="_blank">GitHub</a>`;
      }
    }

    // Convert description ```html code blocks to inline
    // <wtfm-code-block> elements so they render as interactive
    // demos in their natural document flow.
    const cemContext = buildCemContext(elemDocs, resolvedOptions);
    let cleanDescription = elemDocs.description || "";
    let codeIdx = cleanDescription.indexOf("```html");
    while (codeIdx >= 0) {
      const endIdx = cleanDescription.indexOf("```", codeIdx + 7);
      if (endIdx < 0) break;
      const rawHtml = cleanDescription.substring(codeIdx + 7, endIdx).trim();
      let formattedHtml;
      try {
        formattedHtml = await prettier.format(rawHtml, {
          parser: "html",
          htmlWhitespaceSensitivity: "ignore",
        });
      } catch {
        formattedHtml = rawHtml;
      }
      // Encode the HTML as base64 so markdown-it cannot corrupt
      // content inside <script> or <style> blocks (e.g. indented
      // JS being treated as a markdown code fence).
      const encoded = Buffer.from(formattedHtml.trim()).toString("base64");
      const codeBlock = `<wtfm-code-block tag-name="${elemDocs.tagName}" source="${encoded}">
  <script type="application/json">${cemContext.cemJson}</script>
</wtfm-code-block>`;
      cleanDescription =
        cleanDescription.substring(0, codeIdx) +
        codeBlock +
        cleanDescription.substring(endIdx + 3);
      // Advance past the replacement to avoid re-processing
      codeIdx = cleanDescription.indexOf("```html", codeIdx + codeBlock.length);
    }

    let result = `
<div class="doc-header">

\`<${elemDocs.tagName}>\`${githubLink}

</div>

${cleanDescription}
`;

    // ── Resolve section order ────────────────────────────────────
    const docSections = parseDocSections(elemDocs);
    let sectionKeys;

    if (!docSections) {
      sectionKeys = defaultSectionOrder;
    } else {
      const hasAll = docSections.includes("all");
      const exclusions = docSections
        .filter((s) => s.startsWith("-"))
        .map((s) => s.substring(1));
      const inclusions = docSections.filter(
        (s) => s !== "all" && !s.startsWith("-"),
      );

      if (hasAll || inclusions.length === 0) {
        sectionKeys = defaultSectionOrder.filter(
          (k) => !exclusions.includes(k),
        );
      } else {
        sectionKeys = inclusions;
      }
    }

    // ── Render sections ──────────────────────────────────────────
    for (const key of sectionKeys) {
      const renderer = rendererMap.get(key);
      if (!renderer) {
        console.warn(`wtfm: Unknown section renderer "${key}"`);
        continue;
      }
      result += await renderer.render(elemDocs, resolvedOptions);
    }

    return result;
  });

  // ── Global data ──────────────────────────────────────────────
  eleventyConfig.addGlobalData("customElements", customElements);
}
