import markdownIt from "markdown-it";
import mathjax3 from "markdown-it-mathjax3";
import * as prettier from "prettier";
import { readFileSync } from "fs";
import { resolve } from "path";
import {
  defaultRenderers,
  typeRenderers,
  defaultTypeSections,
} from "./section-renderers/index.js";
import { buildCemContext } from "./section-renderers/build-cem-context.js";

/**
 * Reads the @docSections tag from a CEM declaration and returns
 * an array of section keys, or null if not present.
 */
function parseDocSections(decl) {
  const tag = decl.docSections;
  if (!tag) return null;
  const raw = [tag.name, tag.description].filter(Boolean).join(" ");
  if (!raw.trim()) return null;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Builds a function signature string from a function declaration.
 *
 * Example output:
 *   `getEspBus<T extends EspBusEventMap = EspBusEventMap>(): EspBus<T>`
 */
function buildFunctionSignature(decl) {
  let sig = decl.name;

  // Type parameters
  if (decl.typeParameters?.length) {
    sig +=
      "<" +
      decl.typeParameters
        .map((tp) => {
          let s = tp.name;
          if (tp.constraint) s += ` extends ${tp.constraint}`;
          if (tp.default) s += ` = ${tp.default}`;
          return s;
        })
        .join(", ") +
      ">";
  }

  // Parameters
  sig += "(";
  if (decl.parameters?.length) {
    sig += decl.parameters
      .map((p) => {
        let s = p.name;
        if (p.optional) s += "?";
        if (p.type?.text) s += `: ${p.type.text}`;
        if (p.default) s += ` = ${p.default}`;
        return s;
      })
      .join(", ");
  }
  sig += ")";

  // Return type
  if (decl.return?.type?.text) {
    sig += `: ${decl.return.type.text}`;
  }

  return sig;
}

/**
 * WTFM Eleventy plugin — registers shortcodes, filters, and
 * configuration for generating documentation from a Custom
 * Elements Manifest and/or a type manifest.
 *
 * ## Registered shortcodes
 *
 * - **`renderDocs(name)`** — renders the full documentation page
 *   for a web component or type declaration by looking up its
 *   declaration in the CEM (then the type manifest) and running
 *   all configured section renderers.
 * - **`inlineSvg(fileName)`** — reads an SVG file from `assetsDir`
 *   and returns its content inline (with the XML declaration stripped).
 *
 * ## Registered filters
 *
 * - **`asset(name)`** — maps a logical asset name (e.g. `"docs.js"`)
 *   to its hashed filename via the asset manifest.
 *
 * ## Global data
 *
 * - **`customElements`** — the parsed Custom Elements Manifest object.
 * - **`typeManifest`** — the parsed type manifest object (when provided).
 *
 * @param {object} eleventyConfig - The Eleventy configuration object
 *   provided by Eleventy's plugin system.
 *
 * @param {object} options - Plugin options.
 *
 * @param {string} options.cemPath - Absolute or project-relative path
 *   to the `custom-elements.json` file generated by
 *   `@custom-elements-manifest/analyzer`. This is the only required
 *   option.
 *
 * @param {string} [options.typeManifestPath] - Absolute or
 *   project-relative path to the `type-manifest.json` file generated
 *   by the WTFM type extractor.  When provided, `renderDocs` can
 *   also render documentation for non-element declarations
 *   (interfaces, type aliases, const objects, functions).
 *
 * @param {string[]} [options.excludeAttributes=[]] - Attribute names
 *   to hide from the generated documentation. Useful for excluding
 *   internal or inherited attributes that consumers don't need to see.
 *   For example, passing `["variant", "scheme"]` would suppress those
 *   attributes from every component's docs.
 *
 * @param {Object<string, string[]>} [options.attributeExceptions={}] -
 *   Overrides for `excludeAttributes` on a per-tag basis. Keys are
 *   attribute names (must also appear in `excludeAttributes`), values
 *   are arrays of tag names where that attribute should still be shown.
 *
 *   Example: to exclude `"scheme"` globally but still show it on
 *   `<my-root>`:
 *   ```js
 *   {
 *     excludeAttributes: ["scheme"],
 *     attributeExceptions: { "scheme": ["my-root"] },
 *   }
 *   ```
 *
 * @param {string} [options.assetsDir="assets"] - Directory used to
 *   resolve filenames passed to the `inlineSvg` shortcode.
 *
 * @param {function} [options.githubLinkTemplate] - Optional function
 *   that receives a GitHub URL string and returns an HTML string for
 *   the source-code link shown in each component's doc header.
 *   When omitted, a simple `<a href="..." target="_blank">GitHub</a>`
 *   link is generated.
 *
 *   Signature: `(url: string) => string`
 *
 * @param {(string|{key: string})[]} [options.sections] - Array of
 *   section keys (or objects with a `key` property) defining the
 *   default rendering order.  When omitted, the built-in order is
 *   used: `slots`, `attributes`, `methods`, `events`, `css-parts`,
 *   `css-properties`.
 *
 *   Individual components can override this order via the
 *   `@docSections` JSDoc tag in their source:
 *   - `@docSections all, -methods` — render all defaults except methods
 *   - `@docSections slots, attributes` — render only those two sections
 *
 * @param {object[]} [options.customRenderers] - Array of custom section
 *   renderer objects to register alongside the built-in renderers.
 *   Each renderer must conform to the `SectionRenderer` interface:
 *
 *   ```js
 *   {
 *     key: "my-section",         // unique section identifier
 *     async render(decl, options) {
 *       // decl  — CEM declaration for the component
 *       // options — resolved plugin options
 *       return "## My Section\n\nContent here.\n";
 *     }
 *   }
 *   ```
 *
 *   Custom renderers with a `key` matching a built-in renderer will
 *   replace that built-in. To include custom sections in the output,
 *   add their keys to the `sections` option or use `@docSections` in
 *   the component source.
 */
export default function wtfmPlugin(eleventyConfig, options = {}) {
  const {
    cemPath,
    typeManifestPath,
    excludeAttributes = [],
    attributeExceptions = {},
    assetsDir = "assets",
    githubLinkTemplate,
    sections,
    customRenderers,
  } = options;

  // ── Resolved options (passed to every renderer) ───────────────
  const resolvedOptions = {
    ...options,
    excludeAttributes,
    attributeExceptions,
    assetsDir,
    githubLinkTemplate,
  };

  // ── Build the renderer registry ───────────────────────────────
  const rendererMap = new Map();
  for (const r of [...defaultRenderers, ...typeRenderers]) {
    rendererMap.set(r.key, r);
  }
  if (customRenderers) {
    for (const r of customRenderers) {
      rendererMap.set(r.key, r);
    }
  }

  // Short aliases for commonly used section keys so @docSections
  // can use either the full key or the abbreviation.
  const KEY_ALIASES = {
    cssprops: "css-properties",
    cssparts: "css-parts",
  };

  // Resolve the default section order BEFORE adding built-in alias
  // entries to rendererMap, so aliases in the sections option are
  // canonicalized correctly. (If we added aliases first,
  // rendererMap.has("cssprops") would be true, preventing
  // canonicalization and breaking exclusion matching.)
  //
  // Custom renderers registered under an alias key are preserved —
  // only keys that aren't already in rendererMap get canonicalized.
  const rawSectionOrder = sections
    ? sections.map((s) => (typeof s === "string" ? s : s.key))
    : defaultRenderers.map((r) => r.key);
  const defaultSectionOrder = rawSectionOrder.map((k) =>
    rendererMap.has(k) ? k : (KEY_ALIASES[k] ?? k),
  );

  // Now add built-in alias entries so @docSections inclusions work
  // with either the alias or canonical key.
  for (const [alias, canonical] of Object.entries(KEY_ALIASES)) {
    if (!rendererMap.has(alias) && rendererMap.has(canonical)) {
      rendererMap.set(alias, rendererMap.get(canonical));
    }
  }

  // ── Load the Custom Elements Manifest ────────────────────────
  let customElements;
  try {
    customElements = JSON.parse(readFileSync(cemPath, "utf-8"));
  } catch (e) {
    console.warn("wtfm: Could not read custom-elements.json at", cemPath);
    customElements = { modules: [] };
  }

  // ── Load the Type Manifest (optional) ─────────────────────────
  let typeManifest;
  if (typeManifestPath) {
    try {
      typeManifest = JSON.parse(readFileSync(typeManifestPath, "utf-8"));
    } catch (e) {
      console.warn("wtfm: Could not read type-manifest.json at", typeManifestPath);
      typeManifest = { modules: [] };
    }
  } else {
    typeManifest = { modules: [] };
  }

  // ── Markdown-it with mathjax3 ────────────────────────────────
  const mdOptions = {
    html: true,
    breaks: false,
    linkify: true,
  };
  const markdownLib = markdownIt(mdOptions).use(mathjax3);
  eleventyConfig.setLibrary("md", markdownLib);

  // ── Markdown filter for JS templates ────────────────────────
  // Allows `.11ty.js` templates to render markdown through the
  // same shared markdown-it instance registered above:
  //   return this.renderMarkdown(someMarkdownString);
  eleventyConfig.addShortcode("renderMarkdown", function (content) {
    return markdownLib.render(content ?? "");
  });

  // ── Asset filter ─────────────────────────────────────────────
  eleventyConfig.addFilter("asset", function (value) {
    const manifest = this.data.manifest;
    if (manifest && manifest[value]) {
      return `${manifest[value]}`;
    }

    console.warn("Asset not found in manifest: " + value);
  });

  // ── Inline SVG shortcode ─────────────────────────────────────
  eleventyConfig.addShortcode("inlineSvg", function (fileName) {
    const svgPath = resolve(assetsDir, fileName);
    try {
      return readFileSync(svgPath, "utf-8").replace(/<\?xml[^?]*\?>\s*/, "");
    } catch (e) {
      console.warn("SVG not found: " + svgPath);
      return "";
    }
  });

  // ── renderDocs shortcode ─────────────────────────────────────
  eleventyConfig.addShortcode("renderDocs", async function (declName) {
    // ── 1. Look up declaration ───────────────────────────────────
    // Search the CEM first, then fall back to the type manifest.
    let decl;
    let isComponentDecl = false;

    for (const mod of customElements.modules) {
      decl = mod.declarations?.find((d) => d.name === declName);
      if (decl) {
        isComponentDecl = !!decl.tagName;
        break;
      }
    }

    if (!decl) {
      for (const mod of typeManifest.modules) {
        decl = mod.declarations?.find((d) => d.name === declName);
        if (decl) break;
      }
    }

    if (!decl) {
      console.warn("wtfm: No entry found for", declName);
      return "";
    }

    // ── 2. Build header & description ────────────────────────────
    let result;

    if (isComponentDecl) {
      // ── Component header with <tag-name> and optional GitHub link
      const githubUrl = decl.github?.name;
      let githubLink = "";
      if (githubUrl) {
        if (githubLinkTemplate) {
          githubLink = githubLinkTemplate(githubUrl);
        } else {
          githubLink = `<a href="${githubUrl}" target="_blank">GitHub</a>`;
        }
      }

      // Convert description ```html code blocks to inline
      // <wtfm-code-block> elements so they render as interactive
      // demos in their natural document flow.
      const cemContext = buildCemContext(decl, resolvedOptions);
      let cleanDescription = decl.description || "";
      let codeIdx = cleanDescription.indexOf("```html");
      while (codeIdx >= 0) {
        const endIdx = cleanDescription.indexOf("```", codeIdx + 7);
        if (endIdx < 0) break;
        const rawHtml = cleanDescription.substring(codeIdx + 7, endIdx).trim();
        let formattedHtml;
        try {
          formattedHtml = await prettier.format(rawHtml, {
            parser: "html",
            htmlWhitespaceSensitivity: "ignore",
          });
        } catch {
          formattedHtml = rawHtml;
        }
        // Encode the HTML as base64 so markdown-it cannot corrupt
        // content inside <script> or <style> blocks (e.g. indented
        // JS being treated as a markdown code fence).
        const encoded = Buffer.from(formattedHtml.trim()).toString("base64");
        const codeBlock = `<wtfm-code-block tag-name="${decl.tagName}" source="${encoded}">
  <script type="application/json">${cemContext.cemJson}</script>
</wtfm-code-block>`;
        cleanDescription =
          cleanDescription.substring(0, codeIdx) +
          codeBlock +
          cleanDescription.substring(endIdx + 3);
        // Advance past the replacement to avoid re-processing
        codeIdx = cleanDescription.indexOf("```html", codeIdx + codeBlock.length);
      }

      result = `
<div class="doc-header">

\`<${decl.tagName}>\`${githubLink}

</div>

${cleanDescription}
`;
    } else {
      // ── Type declaration header ────────────────────────────────
      let headerName;

      if (decl.kind === "function") {
        // Show the full function signature
        headerName = buildFunctionSignature(decl);
      } else {
        headerName = decl.name;
      }

      const githubUrl = decl.github?.name;
      let githubLink = "";
      if (githubUrl) {
        if (githubLinkTemplate) {
          githubLink = githubLinkTemplate(githubUrl);
        } else {
          githubLink = `<a href="${githubUrl}" target="_blank">GitHub</a>`;
        }
      }

      result = `
<div class="doc-header">

\`${headerName}\`${githubLink}

</div>

${decl.description || ""}
`;

      // For type aliases, show the type expression as a code block
      if (decl.kind === "type-alias" && decl.type?.text) {
        result += `
\`\`\`ts
type ${decl.name} = ${decl.type.text}
\`\`\`
`;
      }

      // For functions, show the return type
      if (
        decl.kind === "function" &&
        decl.return?.type?.text &&
        decl.return?.description
      ) {
        result += `
**Returns** \`${decl.return.type.text}\` — ${decl.return.description}
`;
      }
    }

    // ── 3. Resolve section order ────────────────────────────────
    const docSections = parseDocSections(decl);
    let sectionKeys;

    // Determine the appropriate default section list
    const kindDefaults = isComponentDecl
      ? defaultSectionOrder
      : defaultTypeSections[decl.kind] ?? [];

    if (!docSections) {
      sectionKeys = kindDefaults;
    } else {
      // Resolve aliases so abbreviations like "cssprops" work
      // consistently. Inclusions only resolve when the key isn't
      // already a registered renderer — so a custom renderer under
      // the alias name is not bypassed. Exclusions include both the
      // alias and its canonical form so filtering works regardless
      // of which form kindDefaults uses.
      const resolveKey = (key) =>
        rendererMap.has(key) ? key : (KEY_ALIASES[key] ?? key);

      const hasAll = docSections.includes("all");
      const exclusionSet = new Set();
      for (const s of docSections) {
        if (!s.startsWith("-")) continue;
        const raw = s.substring(1);
        // Include both the raw key and its canonical form so the
        // exclusion matches regardless of which is in kindDefaults.
        exclusionSet.add(raw);
        if (KEY_ALIASES[raw]) exclusionSet.add(KEY_ALIASES[raw]);
      }
      const inclusions = docSections
        .filter((s) => s !== "all" && !s.startsWith("-"))
        .map(resolveKey);

      if (hasAll || inclusions.length === 0) {
        sectionKeys = kindDefaults.filter(
          (k) => !exclusionSet.has(k),
        );
      } else {
        sectionKeys = inclusions;
      }
    }

    // ── 4. Render sections ──────────────────────────────────────
    for (const key of sectionKeys) {
      const renderer = rendererMap.get(key);
      if (!renderer) {
        console.warn(`wtfm: Unknown section renderer "${key}"`);
        continue;
      }
      result += await renderer.render(decl, resolvedOptions);
    }

    return result;
  });

  // ── Global data ──────────────────────────────────────────────
  eleventyConfig.addGlobalData("customElements", customElements);
  if (typeManifestPath) {
    eleventyConfig.addGlobalData("typeManifest", typeManifest);
  }
}
